// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDataDirectory() {
  return window['go']['main']['App']['ChangeDataDirectory']();
}

export function CompleteSetup(arg1) {
  return window['go']['main']['App']['CompleteSetup'](arg1);
}

export function GetCurrentDataDir() {
  return window['go']['main']['App']['GetCurrentDataDir']();
}

export function GetSuggestedDataDir() {
  return window['go']['main']['App']['GetSuggestedDataDir']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NeedsSetup() {
  return window['go']['main']['App']['NeedsSetup']();
}

export function SelectDataDirectory() {
  return window['go']['main']['App']['SelectDataDirectory']();
}
