// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function ChangeDataDirectory():Promise<application.Result_string_>;

export function CompleteSetup(arg1:string):Promise<application.Result_bool_>;

export function GetCurrentDataDir():Promise<string>;

export function GetSuggestedDataDir():Promise<string>;

export function GetSystemTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function NeedsSetup():Promise<boolean>;

export function SelectDataDirectory():Promise<application.Result_string_>;
